# @package _global_
defaults:
  - override /base: hlabel_classification
  - override /callbacks: hlabel_classification
  - override /data: openvino
  - override /model: hlabel_mmpretrain

data:
  data_format: datumaro
  test_subset:
    batch_size: 128

model:
  otx_model:
    _target_: otx.core.model.entity.classification.OVHlabelClassificationModel
    config:
      model_name: openvino.xml
      async_inference: True
      use_throughput_mode: False
      model_type: Classification
      head:
        num_classes: 7
    num_classes: 7
